set(HIMBAECHEL_UARCHES "example")
foreach(uarch ${HIMBAECHEL_UARCHES})
    aux_source_directory(${family}/uarch/${uarch} UARCH_FILES)
    foreach(target ${family_targets})
        target_sources(${target} PRIVATE ${UARCH_FILES})
    endforeach()
endforeach(uarch)
